### ISSUE TITLE
ClassCastException with subGraph

### ISSUE THREAD

**Issue by parkan** [mpollmeier/gremlin-scala#134]
I'm seeing this behavior with the subGraph step:

```
scala> graph.E().subgraph("sg").cap("sg").head
java.lang.ClassCastException: org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerGraph cannot be cast to org.apache.tinkerpop.gremlin.structure.Edge
  ... 43 elided
scala> graph.E().subgraph("sg").cap("sg").headOption
res33: Option[gremlin.scala.Edge] = Some(tinkergraph[vertices:5 edges:4])
```

I can resolve this by casting with `head`:

```
scala> graph.E().subgraph("sg").cap("sg").head.asInstanceOf[TinkerGraph]
res35: org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerGraph = tinkergraph[vertices:5 edges:4]
```

but not with `headOption`:
```
scala> graph.E().subgraph("sg").cap("sg").headOption.map(g => g.asInstanceOf[TinkerGraph])
java.lang.ClassCastException: org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerGraph cannot be cast to org.apache.tinkerpop.gremlin.structure.Edge
  at $anonfun$1.apply(<console>:18)
  at scala.Option.map(Option.scala:146)
  ... 43 elided
```

I don't really understand how an `Option[gremlin.scala.Edge]` can hold a `TinkerGraph` at runtime so I'm not sure how to debug this. Is this not the right way to get subgraph side effects out?

**Comment by mpollmeier** [comment]
Thanks for reporting this - I fixed it in the above mentioned commit. TraversalSpec show the usage. 

If Travis CI and yourself are happy with this I will release a new version - let me know!

Btw. the reason for this weired behaviour of `headOption` is the JVM's type erasure: while the compiler does check that you've got an `Option[Edge]`, this gets erased after compilation, and at runtime all the JVM cares about is that it's an option... :(

**Comment by parkan** [comment]
Thanks for the quick fix and the added specs! Erasure makes sense as the culprit though to be honest I still don't quite understand the casting behavior.

Either way, looks good to me, we are ready to receive new release whenever you want to cut.

**Comment by mpollmeier** [comment]
just released 3.1.1-incubating.1 - should appear in mvn central within a few hours

the reason you had to cast was because subgraph and cap didn't work nicely together before, that's what the commit fixed. by casting you made the compiler happy, however that didn't fix the runtime (mis)behaviour.

**Comment by parkan** [comment]
Ah I see, so the type parameter on StepLabel carries type information into the new `cap`, which emits `GremlinScala[Graph, Labels]`, which then agrees with the actual output at runtime, right?

Works as intended now.

**Comment by mpollmeier** [comment]
That's right. Glad to hear!
